#!/usr/bin/env bash

# Usage: brightness.sh [up|down]

case $1 in
    up)
        brightnessctl -e4 -n2 set 5%+
        ;;
    down)
        brightnessctl -e4 -n2 set 5%-
        ;;
esac

BRIGHTNESS=$(brightnessctl -m | cut -d, -f4 | tr -d '%')

notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -h int:value:"$BRIGHTNESS" "Brightness: $BRIGHTNESS%" -i display-brightness-symbolic
